"""Native-vs-Python parity gate: poses, evaluation and gap classes (#626).

Since #554 the native backend is the default solve path, so every shipped
arm's native ``solve()`` is held to the Python path, and where the two
disagree on a 6R arm, to the chart-free branch oracle (``tests/_branch_oracle``).

Poses
    Every arm gets the same deterministic strata (``poses``). ``uniform`` is
    in-limits uniform sampling; the others target the regions where the two
    backends' numerics diverge and uniform sampling almost never lands:

    - ``near_limit``: one to three limited joints placed *exactly* at a limit,
      or 1e-9 / 1e-6 inside it (``LIMIT_OFFSETS``, cycled).
    - ``near_singular``: a seeded coordinate descent on sigma_min(J) over a
      per-joint grid (the grid includes both limits), then every other pose
      nudged off the minimiser by 1e-8, 1e-6 or 1e-4. The descent is an
      optimisation whose result can move by an ulp between platforms, so its
      output is committed (``POSES_FILE``, regenerated by
      ``scripts/regen_native_parity.py``) instead of recomputed.
    - ``at_pi``: joints whose range reaches +-pi placed at +-pi or 1e-9 inside.
    - ``tight_selfmotion`` (7R only): three or four joints 0.05 % to 5 % of
      their range from a limit, which squeezes the in-limit self-motion.

    The other strata are drawn from ``numpy.random.default_rng`` seeded with
    ``SEED`` and the arm and stratum names, so they reproduce exactly.

Assertions (``evaluate``), in the default (``respect_limits=True``) and raw
(``respect_limits=False``) modes, geometric set only (``enumerate_windings=
False``: winding lifts are a deterministic function of the limits applied after
the solve, tested in ``tests/test_winding_enumeration.py``):

    a. soundness: every native solution closes FK within the default policy's
       ``subproblem_numerical`` (the documented closure contract), and in the
       default mode lies within the joint limits widened by ``LIMIT_SLACK``;
       every solution of either backend reports the ``fk_residual`` of the
       ``q`` it returns, within ``RESIDUAL_TOL`` (#645);
    b. emptiness: the default solve is never empty on native while it is not
       on Python;
    c. 6R coverage: the analytic solve (``allow_rescue=False``) on native
       contains every analytic Python solution, unless ``_Pose.excused``
       shows the missing one is not a branch native lacks;
    d. 7R coverage: the same, except at a kinematic singularity
       (``SEVEN_R_SINGULAR``), where the backends sample a larger continuum
       at their own points and only emptiness is asserted;
    e. the reverse direction of b and c (Python covers native), for 6R.

Solutions match within ``MATCH_TOL`` (L-infinity, on the circle). Every
violation is attributed to one class of ``CLASSES`` by ``_Pose.lacks``, from
evidence that does not depend on which test is asking: whether the missing
solution came from its backend's rescue or in-limits resolver, whether the
other backend's raw set has it just across a limit, and the arm's solver
family. A violation no rule explains is class ``NEW``, which no test expects.
"""

from __future__ import annotations

import copy
import importlib
import json
from collections.abc import Callable
from dataclasses import dataclass, field
from functools import cache
from pathlib import Path
from typing import Any

import numpy as np
from numpy.typing import NDArray

from ssik.core.tolerances import DEFAULT_TOLERANCE_POLICY
from ssik.postprocess import _LIMIT_BAND
from ssik.prebuilt import list_arms
from ssik.prebuilt._manifest import load_manifest
from ssik.refinement import is_same_root, kinbody_jacobian, same_root_floor

__all__ = [
    "CLASSES",
    "NEW",
    "Gap",
    "evaluate",
    "poses",
]

Q = NDArray[np.float64]

_TWO_PI = 2.0 * np.pi
_DATA = Path(__file__).parent / "data"
POSES_FILE = _DATA / "native_parity_poses.json"
ORACLE_FILE = _DATA / "native_parity_oracle.json"

SEED = 626

# Poses per stratum. The fast tier is a prefix of the full tier plus the
# committed witness poses of every known gap on every platform (``fast_pins``
# in POSES_FILE), so on each platform both tiers fail the same (arm, class)
# cells.
FULL = {"uniform": 200, "near_limit": 48, "near_singular": 48, "at_pi": 24, "tight_selfmotion": 32}
FAST = {"uniform": 6, "near_limit": 6, "near_singular": 4, "at_pi": 3, "tight_selfmotion": 3}
TIERS = {"full": FULL, "fast": FAST}

LIMIT_OFFSETS = (0.0, 1e-9, 1e-6)

# Gap classes of #626, each owned by one issue.
CLASSES = {
    "A": (615, "native spherical-shoulder has no in-limits resolver"),
    "B": (621, "native srs_polished returns out-of-limits configurations"),
    "C": (617, "native RR jointlock has no empty-gated rescue"),
    "D": (622, "the T-perturbation rescue differs between backends"),
    "E": (623, "a native core drops a branch near a singularity"),
    "F": (632, "an exact-limit angle lands beyond the round-off limit band on one backend"),
    "G": (544, "native HP jointlock eigensolve loses roots"),
    "I": (462, "native srs_polished in-limits resolver under-samples the feasible swivel arc"),
    "J": (630, "the Python path drops a branch the native core returns"),
}
NEW = "new"

# Classes whose failing poses are decided by round-off, and so differ between
# machines, not only between Linux and macOS: an exact-limit angle beyond the
# limit band (F, #632). Observed: the same commit's CI runners disagree on which
# of these cells fail. Their known cells are non-strict xfails until that issue
# makes the outcome reproducible; every other class is strict. The rescue (D)
# left this set when both backends came to share one deterministic definition
# (#622); a rescued solution that lands exactly on a limit is an F case
# (``_Pose.across_limit``). F stays after #624 made a limit inclusive up to
# round-off and #636 polished accepted general_6r solutions to machine
# precision. What is left is an exact-limit angle at a singular pose
# (sigma_min < 1e-4, a multiple root accurate to ~sqrt(round-off), where the
# polish declines), a Python-path general_6r solution that only the
# near-miss refinement recovered (accurate to its 1e-5 gate: a near-repeated
# root the repeated-root split does not engage on, #640), and the OpenArm SRS
# elbow sign. The side of the limit these land on follows the machine's LAPACK
# kernels, and the cells differ between Linux and macOS.
ROUNDOFF_CLASSES = frozenset({"F"})

# Known cells of a strict class that also differ between CI runners of one
# platform, as (direction, class, arm): non-strict like the round-off class,
# until the named issue makes them reproducible. Record them under the ``ci``
# key of the arm's ``cells`` (scripts/regen_native_parity.py).
#   fanuc_crx10ialp near_singular/8: a 4-fold near-repeated root the split does
#   not engage on, so Python recovers one branch only by the near-miss
#   refinement, 2e-3 from native's; whether the two are the same root by the
#   midpoint test follows the runner (#640).
RUNNER_DEPENDENT_CELLS = frozenset(
    {
        ("forward", "E", "fanuc_crx10ialp_ik"),
        ("reverse", "J", "fanuc_crx10ialp_ik"),
    }
)

# a. FK closure every returned solution must meet: the default policy's
# acceptance gate, documented in README ("How to read fk_residual"). Some
# solvers gate tighter internally, but the +-pi representative snap (#601)
# runs after that gate and may move a joint by up to 1e-6.
FK_TOL = DEFAULT_TOLERANCE_POLICY.subproblem_numerical

# a. How far a reported fk_residual may differ from ||FK(q) - T||_F at the
# returned q: round-off (measured within 5e-15), not the up-to-1e-6 moves of the
# +-pi snap and the limit clamp, after which the residual is re-measured (#645).
RESIDUAL_TOL = 1e-12

# a. How far outside a joint limit a default-mode solution may lie: not at
# all. A value within round-off of a limit is reported as exactly the limit
# (#624, docs/api.md "Joint limits"), so every returned angle is in limits.
LIMIT_SLACK = 0.0

# Two solutions are the same configuration within this L-infinity distance,
# every joint compared on the circle (a joint's 2*pi representative is fixed
# by the winding stage, not by the solver). 6R: the artifact conformance
# gate's radius. 7R: a solution samples a one-dimensional self-motion, and the
# polished families land their samples ~1e-3 apart between backends (#550);
# distinct samples are 2*pi/16 apart, so 1e-2 still tells them apart.
MATCH_TOL = {6: 1e-3, 7: 1e-2}

# d. A 7R pose whose configuration has sigma_min(J) below this is a kinematic
# singularity: the self-motion set gains a dimension there (an SRS elbow at
# full stretch frees q3 + q5), and each backend samples the extra continuum at
# its own points, so solution-for-solution coverage is not defined. Emptiness
# is still asserted there.
SEVEN_R_SINGULAR = 1e-6

# c. Oracle adjudication radius: a solution belongs to an oracle branch, and a
# branch is recovered by a backend, within this distance.
ADJ_TOL = 1e-3

# c. A 6R solution whose Jacobian has sigma_min at least this is a regular
# root; below it the solution may sit on a fold or a continuum, and only the
# oracle can tell.
REGULAR_SIGMA = 1e-3

# False makes every adjudication a live oracle run (the regeneration script).
USE_COMMITTED_ORACLE = True


# --------------------------------------------------------------------- arms


@cache
def _arm_paths() -> dict[str, str]:
    return {a.name: a.import_path for a in list_arms()}


def arm_names() -> list[str]:
    return sorted(_arm_paths())


def module(arm: str) -> Any:
    return importlib.import_module(_arm_paths()[arm])


def family(arm: str) -> str:
    """The solver family, with jointlock split by its locked-6R core."""
    solver = load_manifest()[arm].solver
    if solver == "jointlock.seven_r":
        from ssik._native import _HP_JOINTLOCK_ARMS

        return "jointlock.hp" if arm in _HP_JOINTLOCK_ARMS else "jointlock.rr"
    return solver


def ranges(kb: Any) -> tuple[Q, Q, NDArray[np.bool_]]:
    """Per-joint (lo, hi, has_limit); continuous joints span [-pi, pi]."""
    lo = np.array([j.limits[0] if j.limits else -np.pi for j in kb.joints], dtype=np.float64)
    hi = np.array([j.limits[1] if j.limits else np.pi for j in kb.joints], dtype=np.float64)
    has = np.array([j.limits is not None for j in kb.joints])
    return lo, hi, has


def sigma_min(kb: Any, q: Q) -> float:
    """Smallest of the six singular values of the spatial Jacobian."""
    return float(np.linalg.svd(kinbody_jacobian(kb, q), compute_uv=False)[5])


# -------------------------------------------------------------------- poses


def _rng(arm: str, stratum: str) -> np.random.Generator:
    return np.random.default_rng([SEED, *arm.encode(), *stratum.encode()])


def _uniform(arm: str, kb: Any, n: int) -> list[Q]:
    lo, hi, _ = ranges(kb)
    rng = _rng(arm, "uniform")
    return [rng.uniform(lo, hi) for _ in range(n)]


def _near_limit(arm: str, kb: Any, n: int) -> list[Q]:
    lo, hi, has = ranges(kb)
    rng = _rng(arm, "near_limit")
    limited = np.flatnonzero(has)
    out = []
    for k in range(n):
        q = rng.uniform(lo, hi)
        eps = LIMIT_OFFSETS[k % len(LIMIT_OFFSETS)]
        for i in rng.choice(
            limited, size=min(int(rng.integers(1, 4)), len(limited)), replace=False
        ):
            q[i] = lo[i] + eps if rng.random() < 0.5 else hi[i] - eps
        out.append(q)
    return out


def _at_pi(arm: str, kb: Any, n: int) -> list[Q]:
    lo, hi, _ = ranges(kb)
    wide = np.flatnonzero((lo <= -np.pi) | (hi >= np.pi))
    if not len(wide):
        return []
    rng = _rng(arm, "at_pi")
    values = (np.pi, -np.pi, np.pi - 1e-9, -np.pi + 1e-9)
    out = []
    for k in range(n):
        q = rng.uniform(lo, hi)
        for i in rng.choice(wide, size=int(rng.integers(1, min(3, len(wide)) + 1)), replace=False):
            q[i] = float(np.clip(values[(k + i) % len(values)], lo[i], hi[i]))
        out.append(q)
    return out


def _tight_selfmotion(arm: str, kb: Any, n: int) -> list[Q]:
    if len(kb.joints) != 7:
        return []
    lo, hi, has = ranges(kb)
    rng = _rng(arm, "tight_selfmotion")
    limited = np.flatnonzero(has)
    out = []
    for _ in range(n):
        q = rng.uniform(lo, hi)
        for i in rng.choice(
            limited, size=min(int(rng.integers(3, 5)), len(limited)), replace=False
        ):
            eps = (hi[i] - lo[i]) * 10 ** rng.uniform(-3.3, -1.3)
            q[i] = lo[i] + eps if rng.random() < 0.5 else hi[i] - eps
        out.append(q)
    return out


def near_singular(arm: str, kb: Any, n: int) -> list[Q]:
    """Coordinate descent on sigma_min(J): two sweeps over a 25-point grid per
    joint from a seeded uniform start; every other pose is then nudged off the
    minimiser. Only the regeneration script calls this (see module doc)."""
    lo, hi, _ = ranges(kb)
    rng = _rng(arm, "near_singular")
    nudges = (0.0, 1e-8, 0.0, 1e-6, 0.0, 1e-4)
    out = []
    for k in range(n):
        q = rng.uniform(lo, hi)
        for _sweep in range(2):
            best, best_i, best_v = sigma_min(kb, q), -1, 0.0
            for i in range(len(q)):
                for v in np.linspace(lo[i], hi[i], 25):
                    trial = q.copy()
                    trial[i] = v
                    s = sigma_min(kb, trial)
                    if s < best:
                        best, best_i, best_v = s, i, float(v)
            if best_i >= 0:
                q[best_i] = best_v
        nudge = nudges[k % len(nudges)]
        if nudge:
            q = np.clip(q + nudge * rng.standard_normal(len(q)), lo, hi)
        out.append(q)
    return out


_GENERATED: dict[str, Callable[[str, Any, int], list[Q]]] = {
    "uniform": _uniform,
    "near_limit": _near_limit,
    "at_pi": _at_pi,
    "tight_selfmotion": _tight_selfmotion,
}


@cache
def _pose_data() -> dict[str, Any]:
    data: dict[str, Any] = json.loads(POSES_FILE.read_text())
    return data


@cache
def _full_poses(arm: str) -> dict[str, list[Q]]:
    kb = module(arm)._KB
    out = {s: gen(arm, kb, FULL[s]) for s, gen in _GENERATED.items()}
    out["near_singular"] = [np.array(q) for q in _pose_data()["arms"][arm]["near_singular"]]
    return out


def poses(arm: str, tier: str) -> list[tuple[str, Q]]:
    """``(pose id, q)`` for the tier. A pose id is ``"<stratum>/<index>"`` in
    the full tier, so a failure names a pose both tiers share."""
    full = _full_poses(arm)
    ids = [f"{s}/{k}" for s in FULL for k in range(min(TIERS[tier][s], len(full[s])))]
    if tier == "fast":  # every platform's witnesses (scripts/regen_native_parity.py)
        for pins in _pose_data()["arms"][arm]["fast_pins"].values():
            ids += [p for p in pins if p not in ids]
    out = []
    for pid in ids:
        s, k = pid.split("/")
        out.append((pid, full[s][int(k)]))
    return out


# ------------------------------------------------------------------ matching


def _dist(a: Q, b: Q) -> NDArray[np.float64]:
    """Pairwise L-infinity distance, every joint on the circle."""
    d = (a[:, None, :] - b[None, :, :] + np.pi) % _TWO_PI - np.pi
    return np.asarray(np.max(np.abs(d), axis=2))


def unmatched(src: Q, dst: Q, tol: float) -> list[int]:
    """Rows of ``src`` with no row of ``dst`` within ``tol``."""
    if not len(src):
        return []
    if not len(dst):
        return list(range(len(src)))
    return [int(i) for i in np.flatnonzero(~np.any(_dist(src, dst) <= tol, axis=1))]


def _limit_excess(q: Q, lo: Q, hi: Q, has: NDArray[np.bool_]) -> float:
    """How far the configuration's nearest in-range representative lies
    outside its limits (<= 0 when inside); raw-mode coordinates are only one
    representative, so every 2*pi shift is tried."""
    worst = -np.inf
    for i in np.flatnonzero(has):
        k = np.round((np.clip(q[i], lo[i], hi[i]) - q[i]) / _TWO_PI)
        best = min(
            max(lo[i] - v, v - hi[i]) for v in (q[i] + _TWO_PI * (k + d) for d in (-1, 0, 1))
        )
        worst = max(worst, best)
    return float(worst)


# ----------------------------------------------------------------- the oracle


@dataclass(frozen=True)
class Adjudication:
    """The oracle's branch set at one pose (joint limits removed)."""

    stabilized: bool
    branches: Q

    def verdict(self, q: Q, recovered_by: Q) -> str | None:
        """Why a solution one backend lacks is not a gap, or None if it is.

        ``recovered_by`` is the other backend's raw analytic set."""
        if not self.stabilized:
            return "the oracle did not stabilise: not a finite branch set here"
        if not len(self.branches) or unmatched(q[None], self.branches, ADJ_TOL):
            return "not an oracle branch"
        b = self.branches[int(np.argmin(_dist(q[None], self.branches)[0]))]
        if not unmatched(b[None], recovered_by, ADJ_TOL):
            return "a duplicate of a branch the other backend returns"
        return None


@cache
def _oracle_file() -> dict[str, Any]:
    if not USE_COMMITTED_ORACLE or not ORACLE_FILE.exists():
        return {}
    data: dict[str, Any] = json.loads(ORACLE_FILE.read_text())
    return data


def run_oracle(arm: str, q: Q) -> Adjudication:
    from tests._branch_oracle import enumerate_branches

    m = module(arm)
    kb = copy.deepcopy(m._KB)
    for j in kb.joints:  # every branch, not only those an in-limits start reaches
        j.limits = None
    res = enumerate_branches(kb, np.asarray(m.fk(q), dtype=np.float64))
    dof = len(kb.joints)
    return Adjudication(res.stabilized, np.array(res.branches).reshape(-1, dof))


@cache
def adjudicate(arm: str, pid: str) -> Adjudication:
    """The committed adjudication, or a live oracle run for a pose the
    committed file lacks (a platform whose numerics raise a gap elsewhere)."""
    rec = _oracle_file().get("arms", {}).get(arm, {}).get(pid)
    if rec is not None:
        dof = len(module(arm)._KB.joints)
        return Adjudication(rec["stabilized"], np.array(rec["branches"]).reshape(-1, dof))
    q = dict(poses(arm, "full"))[pid]
    return run_oracle(arm, q)


# ---------------------------------------------------------------- evaluation


@dataclass(frozen=True)
class Gap:
    cls: str  # a CLASSES key, or NEW
    check: str  # soundness | emptiness | coverage | reverse
    mode: str  # limits | raw
    pose: str
    detail: str

    def __str__(self) -> str:
        return f"[{self.cls}] {self.check} ({self.mode}) at {self.pose}: {self.detail}"


@dataclass
class Report:
    forward: list[Gap] = field(default_factory=list)
    reverse: list[Gap] = field(default_factory=list)
    oracle_poses: set[str] = field(default_factory=set)  # poses the oracle judged


def _solve(m: Any, t: Q, *, limits: bool, native: bool, rescue: bool) -> tuple[Q, Q]:
    """The solutions' joint vectors and their reported ``fk_residual``s."""
    sols = m.solve(
        t, respect_limits=limits, native=native, allow_rescue=rescue, enumerate_windings=False
    )
    dof = len(m._KB.joints)
    qs = np.array([np.asarray(s.q, dtype=np.float64) for s in sols]).reshape(-1, dof)
    return qs, np.array([s.fk_residual for s in sols], dtype=np.float64)


class _Pose:
    """One pose's solve sets and the classification rules that read them."""

    def __init__(self, arm: str, pid: str, q: Q, rep: Report) -> None:
        self.arm, self.pid, self.rep = arm, pid, rep
        self.m = module(arm)
        self.kb = self.m._KB
        self.dof = len(self.kb.joints)
        self.fam = family(arm)
        self.tol = MATCH_TOL[self.dof]
        self.lo, self.hi, self.has = ranges(self.kb)
        self.t = np.asarray(self.m.fk(q), dtype=np.float64)
        self.floor = same_root_floor(self.t)
        # (mode, backend, rescue) -> solutions, and their reported residuals
        solved = {
            (mode, backend, rescue): _solve(
                self.m, self.t, limits=mode == "limits", native=backend == "native", rescue=rescue
            )
            for mode in ("limits", "raw")
            for backend in ("native", "python")
            for rescue in (True, False)
        }
        self.sets = {key: qs for key, (qs, _) in solved.items()}
        self.residuals = {key: res for key, (_, res) in solved.items()}
        # d. see SEVEN_R_SINGULAR
        self.coverage_defined = self.dof == 6 or sigma_min(self.kb, q) >= SEVEN_R_SINGULAR

    def fk_err(self, q: Q) -> float:
        return float(np.linalg.norm(self.m.fk(q) - self.t))

    def lacks(self, q: Q, mode: str, other: str) -> str | None:
        """The class of an analytic solution the ``other`` backend's analytic
        set lacks in ``mode``, or None when that is not a gap."""
        own = "python" if other == "native" else "native"
        other_raw = self.sets[("raw", other, False)]
        if mode == "limits":
            hits = [o for o in other_raw if not unmatched(q[None], o[None], self.tol)]
            if any(_limit_excess(o, self.lo, self.hi, self.has) > _LIMIT_BAND for o in hits):
                # The other backend has it just across a limit, beyond the band
                # within which it would have put it on the limit (#624).
                return "F"
            if unmatched(q[None], self.sets[("raw", own, False)], self.tol):
                # Not in its own raw set: its in-limits resolver produced it.
                if other == "native" and self.fam.startswith("seven_r.spherical_shoulder"):
                    return "A"
                if other == "native" and self.fam == "seven_r.srs_polished":
                    return "I"
                return NEW
            if hits:
                return NEW  # the other backend has it inside the limits, yet dropped it
        if self.dof == 6 and self.excused(q, other_raw):
            return None
        if other == "python":
            return "J"
        return "G" if self.fam == "jointlock.hp" else "E"

    def excused(self, q: Q, other_raw: Q) -> bool:
        """Whether a 6R solution the other backend lacks is not a missing branch.

        1. The other backend returns the same root at its own accuracy, by the
           #604 midpoint test (FK stays closed between the two). Near a
           singularity a root is ill-conditioned, and two FK-closing copies of
           it can lie far beyond the match radius.
        2. A regular root (J full rank, and its FK error moves it far less than
           the match radius) is an isolated branch by the implicit function
           theorem, so it is never excused.
        3. Near a singular root, the oracle decides (``Adjudication.verdict``).
        """
        r = self.fk_err(q)
        if any(
            is_same_root(q, r, o, self.fk_err(o), self.m.fk, self.t, self.floor) for o in other_raw
        ):
            return True
        s = sigma_min(self.kb, q)
        if s >= REGULAR_SIGMA and r / s <= ADJ_TOL / 10:
            return False
        self.rep.oracle_poses.add(self.pid)
        return adjudicate(self.arm, self.pid).verdict(q, other_raw) is not None

    def across_limit(self, want: Q, other: str) -> bool:
        """Whether every solution of ``want`` is in the ``other`` backend's raw
        set (rescue included) just outside a joint limit: the two backends
        rescued the same configurations, and only the limit filter split them."""
        other_raw = self.sets[("raw", other, True)]
        for q in want:
            hits = [o for o in other_raw if not unmatched(q[None], o[None], self.tol)]
            if not any(_limit_excess(o, self.lo, self.hi, self.has) > _LIMIT_BAND for o in hits):
                return False
        return True

    def check(self, mode: str) -> None:
        pid, rep = self.pid, self.rep
        nat, py = self.sets[(mode, "native", True)], self.sets[(mode, "python", True)]
        nat_a, py_a = self.sets[(mode, "native", False)], self.sets[(mode, "python", False)]

        # a. soundness
        for x in np.vstack([nat, nat_a]):
            r = self.fk_err(x)
            if r > FK_TOL:
                rep.forward.append(Gap(NEW, "soundness", mode, pid, f"FK {r:.1e} at {x.tolist()}"))
            if mode == "limits":
                ex = _limit_excess(x, self.lo, self.hi, self.has)
                if ex > LIMIT_SLACK:
                    rep.forward.append(
                        Gap(
                            "B",
                            "soundness",
                            mode,
                            pid,
                            f"{ex:.1e} rad outside the limits: {x.tolist()}",
                        )
                        if self.fam == "seven_r.srs_polished"
                        else Gap(NEW, "soundness", mode, pid, f"{ex:.1e} rad outside: {x.tolist()}")
                    )

        # a. the reported residual is the returned configuration's (#645)
        for backend, out in (("native", rep.forward), ("python", rep.reverse)):
            for rescue in (True, False):
                key = (mode, backend, rescue)
                for x, reported in zip(self.sets[key], self.residuals[key], strict=True):
                    actual = self.fk_err(x)
                    if abs(reported - actual) > RESIDUAL_TOL:
                        out.append(
                            Gap(
                                NEW,
                                "soundness",
                                mode,
                                pid,
                                f"{backend} fk_residual {reported:.1e}, actual {actual:.1e} "
                                f"at {x.tolist()}",
                            )
                        )

        # b. emptiness, and e. its reverse
        for got, want, want_a, other, out in (
            (nat, py, py_a, "native", rep.forward),
            (py, nat, nat_a, "python", rep.reverse),
        ):
            if len(got) or not len(want):
                continue
            if len(want_a):
                cls = self.lacks(want_a[0], mode, other)
                if cls is None:
                    continue
            elif mode == "limits" and self.across_limit(want, other):
                # Both rescues found it, at a joint limit: an exact-limit tie.
                cls = "F"
            elif other == "native":  # every Python solution came from its rescue
                cls = "C" if self.fam == "jointlock.rr" else "D"
            else:
                cls = "D"
            who = "native" if other == "native" else "Python"
            out.append(
                Gap(
                    cls, "emptiness", mode, pid, f"{who} [] vs {len(want)} ({len(want_a)} analytic)"
                )
            )

        # c/d. coverage of the analytic sets, and e. its reverse (6R only: a
        # redundant 7R backend may sample the self-motion more densely by
        # design, #550)
        if not self.coverage_defined:
            return
        pairs = [(py_a, nat_a, "native", rep.forward)]
        if self.dof == 6:
            pairs.append((nat_a, py_a, "python", rep.reverse))
        for src, dst, other, out in pairs:
            for i in unmatched(src, dst, self.tol):
                cls = self.lacks(src[i], mode, other)
                if cls is not None:
                    who = "native" if other == "native" else "Python"
                    out.append(Gap(cls, "coverage", mode, pid, f"{who} lacks {src[i].tolist()}"))


@cache
def evaluate(arm: str, tier: str) -> Report:
    """Every gap on the tier's poses, each attributed to a class."""
    rep = Report()
    for pid, q in poses(arm, tier):
        pose = _Pose(arm, pid, q, rep)
        for mode in ("limits", "raw"):
            pose.check(mode)
    return rep
