"""Bulletproof validation for the m1013_ik fixture (auto-generated by ``ssik add-arm``).

The arm dispatches to ``ikgeo.general_6r`` (tier 2) per the
current ``ssik.core.dispatcher``. The scaffold below verifies, against the
**shipped artifact** (``ssik.prebuilt.m1013_ik`` -- build it with
``uv run python scripts/regen_artifacts.py --arm m1013_ik`` first):

- URDF loads as a 6-DOF chain (revolute / continuous joints).
- Dispatcher routing is stable.
- **Coverage:** poses sampled across the arm's real joint limits return at
  least one IK for at least ``_MIN_COVERAGE`` of them. This is the gate a
  broken/degenerate arm (0 solutions, locked ``[0, 0]`` limits, wrong ee
  gauge) fails loudly -- "FK closes on every retained IK" is vacuously
  true at zero coverage, so coverage is asserted separately.
- Every returned IK FK-closes within ``_FK_CEILING``.

If the arm has a genuine structural coverage gap (redundant-7R near-
singular poses, etc.), lower ``_MIN_COVERAGE`` here AND add a
``[arms.m1013_ik.known_gaps]`` entry in MANIFEST.toml documenting why.

Source URDF: ``tests/fixtures/m1013_ik.urdf`` (vendored via ``ssik add-arm``).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from ssik._urdf import load_urdf_kinbody_normalized
from ssik.core.dispatcher import dispatch

URDF_PATH = Path(__file__).parent / "fixtures" / "m1013_ik.urdf"

# Fraction of reachable poses that must return >= 1 IK. A broken arm
# returns few/none; this is the coverage floor the gate enforces.
_MIN_COVERAGE = 0.95
_N_COVERAGE_POSES = 64
# Worst-case FK-closure ceiling on returned solutions. Tighten/loosen to
# the arm's numerical floor (closed-form 6R ~1e-12; non-Pieper RR ~1e-6).
_FK_CEILING = 1e-4


def _m1013_ik_kinbody():
    return load_urdf_kinbody_normalized(URDF_PATH, "base_link", "link_6")


def _joint_bounds():
    """(lo, hi) arrays of per-joint sampling bounds from the real URDF
    limits; continuous / limitless joints sample [-pi, pi]."""
    kb = _m1013_ik_kinbody()
    lo, hi = [], []
    for j in kb.joints:
        lim = getattr(j, "limits", None)
        if lim is None:
            lo.append(-np.pi)
            hi.append(np.pi)
        else:
            lo.append(float(lim[0]))
            hi.append(float(lim[1]))
    return np.array(lo), np.array(hi)


# ----------------------------------------------------------------------------
# URDF load + topology + routing (fixture-based, fast)
# ----------------------------------------------------------------------------


def test_m1013_ik_loads_as_6dof() -> None:
    kb = _m1013_ik_kinbody()
    assert len(kb.joints) == 6
    for j in kb.joints:
        assert j.joint_type in ("revolute", "continuous")


def test_m1013_ik_dispatches_to_ikgeo_general_6r() -> None:
    """Dispatcher routing is stable. Updating the dispatcher should
    update this assertion deliberately.
    """
    kb = _m1013_ik_kinbody()
    plan = dispatch(kb)
    assert plan.solver_name == "ikgeo.general_6r"
    assert plan.tier == 2


# ----------------------------------------------------------------------------
# Coverage + FK-closure gate against the SHIPPED artifact (fast, default gate)
# ----------------------------------------------------------------------------


def test_m1013_ik_coverage_and_fk_closure() -> None:
    """Sample poses across the arm's real joint limits, FK + solve with the
    shipped ``module.solve`` (not the raw solver), and assert coverage >=
    ``_MIN_COVERAGE`` and FK closure within ``_FK_CEILING``.

    This is the gate a broken arm fails: 0-coverage (FANUC-M710-style
    conditioning, Kinova-[0,0]-limit lockouts) trips the coverage assert
    instead of passing vacuously.
    """
    art = pytest.importorskip(
        "ssik.prebuilt.m1013_ik",
        reason="build the artifact first: regen_artifacts.py --arm m1013_ik",
    )
    from ssik._validation import assert_solve_coverage

    assert_solve_coverage(
        art,
        min_coverage=_MIN_COVERAGE,
        fk_ceiling=_FK_CEILING,
        n_poses=_N_COVERAGE_POSES,
    )


# ----------------------------------------------------------------------------
# Thorough Hypothesis fuzz against the shipped artifact (slow)
# ----------------------------------------------------------------------------


@pytest.mark.slow
@given(seed=st.integers(min_value=0, max_value=2**31 - 1))
@settings(
    max_examples=200,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture],
)
def test_m1013_ik_random_pose_fk_closure(seed: int) -> None:
    """200 random reachable poses (within real joint limits): at least one
    returned IK FK-closes within ``_FK_CEILING``."""
    art = pytest.importorskip(
        "ssik.prebuilt.m1013_ik",
        reason="build the artifact first: regen_artifacts.py --arm m1013_ik",
    )

    lo, hi = _joint_bounds()
    rng = np.random.default_rng(seed)
    q_star = rng.uniform(lo, hi)
    sols = art.solve(art.fk(q_star))
    assert sols, f"no IK returned for reachable q*={q_star.tolist()}"
    best_fk = min(float(s.fk_residual) for s in sols)
    assert best_fk < _FK_CEILING, f"seed={seed}: best FK={best_fk:.2e} > ceiling"
