"""Bulletproof validation for the openarm_left fixture (auto-generated by ``ssik add-arm``).

The arm dispatches to ``seven_r.srs_polished`` (tier 0) per the
current ``ssik.core.dispatcher``. The scaffold below verifies:

- URDF loads as a 7-DOF revolute chain.
- Dispatcher routing is stable.
- Every retained IK FK-closes ≤ 1e-10 on hand-picked + random
  reachable poses.

Edit this file freely after generation -- the scaffold is a starting
point. For 7R arms with URDF axis drift, consider adding a drift-
documentation test (see ``tests/test_kinova_gen3.py`` /
``tests/test_flexiv_rizon4.py`` for examples).

Source URDF: ``tests/fixtures/openarm_left.urdf`` (vendored via ``ssik add-arm``).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from ssik._urdf import load_urdf_kinbody_normalized
from ssik.core.dispatcher import dispatch
from ssik.kinematics.poe_fk import poe_forward_kinematics

URDF_PATH = Path(__file__).parent / "fixtures" / "openarm_left.urdf"


def _openarm_left_kinbody():
    return load_urdf_kinbody_normalized(
        URDF_PATH, "openarm_left_base_link", "openarm_left_ee_base_link"
    )


# ----------------------------------------------------------------------------
# URDF load + topology
# ----------------------------------------------------------------------------


def test_openarm_left_loads_as_7r() -> None:
    kb = _openarm_left_kinbody()
    assert len(kb.joints) == 7
    for j in kb.joints:
        assert j.joint_type == "revolute"


def test_openarm_left_dispatches_to_seven_r_srs_polished() -> None:
    """Dispatcher routing is stable. Updating the dispatcher should
    update this assertion deliberately.
    """
    kb = _openarm_left_kinbody()
    plan = dispatch(kb)
    assert plan.solver_name == "seven_r.srs_polished"
    assert plan.tier == 0


# ----------------------------------------------------------------------------
# Hand-picked seeded recovery (slow -- IK calls)
# ----------------------------------------------------------------------------


_HAND_PICKED_Q = [
    np.array([0.5521, -0.5424, 0.0924, -0.2111, -0.4561, -0.1827, -0.1149]),
    np.array([-0.1797, 0.1532, 0.0221, 0.3112, 0.2440, 0.5810, 0.1437]),
    np.array([0.6714, -0.6854, 0.6769, -0.7428, -0.6600, -0.5989, -0.0357]),
    np.array([0.6888, 0.0199, 0.3400, 0.0036, -0.4162, 0.6022, -0.6899]),
]


@pytest.mark.slow
@pytest.mark.parametrize("q_star", _HAND_PICKED_Q)
def test_openarm_left_hand_picked_fk_closure(q_star: np.ndarray) -> None:
    """Every reachable hand-picked q* yields at least one IK with FK
    closure ≤ 1e-10.
    """
    kb = _openarm_left_kinbody()
    T_target = poe_forward_kinematics(kb, q_star)
    from ssik.solvers.seven_r import srs_polished

    sols, _ = srs_polished.solve(kb, T_target)
    assert sols, f"no IK returned for reachable q*={q_star.tolist()}"
    best_fk = min(s.fk_residual for s in sols)
    assert best_fk < 1e-10, f"best FK={best_fk:.2e} > 1e-10"


# ----------------------------------------------------------------------------
# Hypothesis fuzz: random reachable poses
# ----------------------------------------------------------------------------


@pytest.mark.slow
@given(seed=st.integers(min_value=0, max_value=2**31 - 1))
@settings(
    max_examples=10,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture],
)
def test_openarm_left_random_pose_fk_closure(seed: int) -> None:
    """10 random q in [-0.8, 0.8] per joint: at least one
    returned IK FK-closes < 1e-10.
    """
    rng = np.random.default_rng(seed)
    q_star = rng.uniform(-0.8, 0.8, size=7)
    kb = _openarm_left_kinbody()
    T_target = poe_forward_kinematics(kb, q_star)
    from ssik.solvers.seven_r import srs_polished

    sols, _ = srs_polished.solve(kb, T_target)
    assert sols, f"no IK returned for random q*={q_star.tolist()}"
    best_fk = min(s.fk_residual for s in sols)
    assert best_fk < 1e-10, f"seed={seed}: best FK={best_fk:.2e} > 1e-10"
