"""Bulletproof validation for the yumi_right_ik fixture (auto-generated by ``ssik add-arm``).

The arm dispatches to ``seven_r.srs_polished`` (tier 0) per the
current ``ssik.core.dispatcher``. The scaffold below verifies, against the
**shipped artifact** (``ssik.prebuilt.yumi_right_ik`` -- build it with
``uv run python scripts/regen_artifacts.py --arm yumi_right_ik`` first):

- URDF loads as a 7-DOF chain (revolute / continuous joints).
- Dispatcher routing is stable.
- **Coverage:** poses sampled across the arm's real joint limits return at
  least one IK for at least ``_MIN_COVERAGE`` of them. This is the gate a
  broken/degenerate arm (0 solutions, locked ``[0, 0]`` limits, wrong ee
  gauge) fails loudly -- "FK closes on every retained IK" is vacuously
  true at zero coverage, so coverage is asserted separately.
- Every returned IK FK-closes within ``_FK_CEILING``.

If the arm has a genuine structural coverage gap (redundant-7R near-
singular poses, etc.), lower ``_MIN_COVERAGE`` here AND add a
``[arms.yumi_right_ik.known_gaps]`` entry in MANIFEST.toml documenting why.

Source URDF: ``tests/fixtures/yumi_right_ik.urdf`` (vendored via ``ssik add-arm``).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from ssik._urdf import load_urdf_kinbody_normalized
from ssik.core.dispatcher import dispatch

URDF_PATH = Path(__file__).parent / "fixtures" / "yumi_right_ik.urdf"

# Fraction of reachable poses that must return >= 1 IK. A broken arm
# returns few/none; this is the coverage floor the gate enforces.
_MIN_COVERAGE = 0.95
_N_COVERAGE_POSES = 64
# Worst-case FK-closure ceiling on returned solutions. Tighten/loosen to
# the arm's numerical floor (closed-form 6R ~1e-12; non-Pieper RR ~1e-6).
_FK_CEILING = 1e-6


def _yumi_right_ik_kinbody():
    return load_urdf_kinbody_normalized(URDF_PATH, "yumi_body", "yumi_link_7_r")


def _joint_bounds():
    """(lo, hi) arrays of per-joint sampling bounds from the real URDF
    limits; continuous / limitless joints sample [-pi, pi]."""
    kb = _yumi_right_ik_kinbody()
    lo, hi = [], []
    for j in kb.joints:
        lim = getattr(j, "limits", None)
        if lim is None:
            lo.append(-np.pi)
            hi.append(np.pi)
        else:
            lo.append(float(lim[0]))
            hi.append(float(lim[1]))
    return np.array(lo), np.array(hi)


# ----------------------------------------------------------------------------
# URDF load + topology + routing (fixture-based, fast)
# ----------------------------------------------------------------------------


def test_yumi_right_ik_loads_as_7dof() -> None:
    kb = _yumi_right_ik_kinbody()
    assert len(kb.joints) == 7
    for j in kb.joints:
        assert j.joint_type in ("revolute", "continuous")


def test_yumi_right_ik_dispatches_to_seven_r_srs_polished() -> None:
    """Dispatcher routing is stable. Updating the dispatcher should
    update this assertion deliberately.
    """
    kb = _yumi_right_ik_kinbody()
    plan = dispatch(kb)
    assert plan.solver_name == "seven_r.srs_polished"
    assert plan.tier == 0


# ----------------------------------------------------------------------------
# Coverage + FK-closure gate against the SHIPPED artifact (fast, default gate)
# ----------------------------------------------------------------------------


def test_yumi_right_ik_coverage_and_fk_closure() -> None:
    """Sample poses across the arm's real joint limits, FK + solve with the
    shipped ``module.solve`` (not the raw solver), and assert coverage >=
    ``_MIN_COVERAGE`` and FK closure within ``_FK_CEILING``.

    This is the gate a broken arm fails: 0-coverage (FANUC-M710-style
    conditioning, Kinova-[0,0]-limit lockouts) trips the coverage assert
    instead of passing vacuously.
    """
    art = pytest.importorskip(
        "ssik.prebuilt.yumi_right_ik",
        reason="build the artifact first: regen_artifacts.py --arm yumi_right_ik",
    )

    lo, hi = _joint_bounds()
    rng = np.random.default_rng(0)
    covered = 0
    worst_fk = 0.0
    for _ in range(_N_COVERAGE_POSES):
        q = rng.uniform(lo, hi)
        sols = art.solve(art.fk(q))
        if sols:
            covered += 1
            worst_fk = max(worst_fk, max(float(s.fk_residual) for s in sols))
    coverage = covered / _N_COVERAGE_POSES
    assert coverage >= _MIN_COVERAGE, (
        f"yumi_right_ik: coverage {coverage:.0%} < {_MIN_COVERAGE:.0%} "
        f"({covered}/{_N_COVERAGE_POSES} reachable poses returned an IK). "
        f"A broken or degenerate arm returns few/no solutions."
    )
    assert worst_fk < _FK_CEILING, (
        f"yumi_right_ik: worst FK {worst_fk:.2e} > {_FK_CEILING:.0e} ceiling"
    )


# ----------------------------------------------------------------------------
# Thorough Hypothesis fuzz against the shipped artifact (slow)
# ----------------------------------------------------------------------------


@pytest.mark.slow
@given(seed=st.integers(min_value=0, max_value=2**31 - 1))
@settings(
    max_examples=200,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture],
)
def test_yumi_right_ik_random_pose_fk_closure(seed: int) -> None:
    """200 random reachable poses (within real joint limits): at least one
    returned IK FK-closes within ``_FK_CEILING``."""
    art = pytest.importorskip(
        "ssik.prebuilt.yumi_right_ik",
        reason="build the artifact first: regen_artifacts.py --arm yumi_right_ik",
    )

    lo, hi = _joint_bounds()
    rng = np.random.default_rng(seed)
    q_star = rng.uniform(lo, hi)
    sols = art.solve(art.fk(q_star))
    assert sols, f"no IK returned for reachable q*={q_star.tolist()}"
    best_fk = min(float(s.fk_residual) for s in sols)
    assert best_fk < _FK_CEILING, f"seed={seed}: best FK={best_fk:.2e} > ceiling"
