"""Prebuilt per-arm IK artifacts, organized by vendor.

Discover what ships without importing any artifact::

    import ssik
    ssik.list_arms()                  # all arms (name, vendor, class, DOF)
    ssik.list_arms(vendor="fanuc")    # filter to one vendor

Preferred import (#421)::

    from ssik.prebuilt.universal_robots import ur5_ik
    from ssik.prebuilt.fanuc import crx10ia_ik

Legacy flat imports keep working, unchanged, forever -- a lazy alias finder
maps every legacy flat name to its vendor module::

    from ssik.prebuilt import ur5_ik, fanuc_crx10ia_ik   # still works
    importlib.import_module("ssik.prebuilt.ur5_ik")       # still works

``import ssik``, ``import ssik.prebuilt`` and ``import ssik.prebuilt.<vendor>``
load zero arm artifacts; only ``...<vendor>.<model>_ik`` loads one.
"""

from __future__ import annotations

import importlib
import importlib.abc
import importlib.machinery
import sys
from types import ModuleType
from typing import NamedTuple

# GENERATED by scripts/regen_artifacts.py -- legacy flat basename ->
# "<vendor>.<model>_ik" (relative to this package). Do not hand-edit.
_LEGACY_ALIASES: dict[str, str] = {
    "ur5_ik": "universal_robots.ur5_ik",
    "ur3e_ik": "universal_robots.ur3e_ik",
    "ur5e_ik": "universal_robots.ur5e_ik",
    "ur10e_ik": "universal_robots.ur10e_ik",
    "ur16e_ik": "universal_robots.ur16e_ik",
    "ur20_ik": "universal_robots.ur20_ik",
    "ur30_ik": "universal_robots.ur30_ik",
    "puma560_ik": "unimation.puma560_ik",
    "jaco2_ik": "kinova.jaco2_ik",
    "iiwa14_ik": "kuka.iiwa14_ik",
    "gen3_ik": "kinova.gen3_ik",
    "franka_panda_ik": "franka.panda_ik",
    "xarm7_ik": "ufactory.xarm7_ik",
    "xarm6_ik": "ufactory.xarm6_ik",
    "z1_ik": "unitree.z1_ik",
    "piper_ik": "agilex.piper_ik",
    "rizon4_ik": "flexiv.rizon4_ik",
    "kassow_kr810_ik": "kassow.kr810_ik",
    "rizon10_ik": "flexiv.rizon10_ik",
    "fanuc_crx3ia_ik": "fanuc.crx3ia_ik",
    "fanuc_crx5ia_ik": "fanuc.crx5ia_ik",
    "fanuc_crx10ia_ik": "fanuc.crx10ia_ik",
    "fanuc_crx10ialp_ik": "fanuc.crx10ialp_ik",
    "fanuc_crx20ial_ik": "fanuc.crx20ial_ik",
    "fanuc_crx30ia_ik": "fanuc.crx30ia_ik",
    "fanuc_crx10ial_ik": "fanuc.crx10ial_ik",
    "yam_ik": "i2rt.yam_ik",
    "big_yam_ik": "i2rt.big_yam_ik",
    "fr3_ik": "franka.fr3_ik",
    "openarm_left_ik": "openarm.left_ik",
    "openarm_right_ik": "openarm.right_ik",
    "r1pro_left_ik": "galaxea.r1pro_left_ik",
    "r1pro_right_ik": "galaxea.r1pro_right_ik",
    "standardbots_thor_ik": "standard_bots.thor_ik",
    "standardbots_core_ik": "standard_bots.core_ik",
    "standardbots_spark_ik": "standard_bots.spark_ik",
    "gen3_lite_ik": "kinova.gen3_lite_ik",
    "ur7e_ik": "universal_robots.ur7e_ik",
    "ur12e_ik": "universal_robots.ur12e_ik",
    "ur15_ik": "universal_robots.ur15_ik",
    "ur18_ik": "universal_robots.ur18_ik",
    "yumi_left_ik": "abb.yumi_left_ik",
    "yumi_right_ik": "abb.yumi_right_ik",
    "fanuc_m710ic_ik": "fanuc.m710ic_ik",
    "j2s6s300_ik": "kinova.j2s6s300_ik",
    "iiwa7_ik": "kuka.iiwa7_ik",
    "j2s7s300_ik": "kinova.j2s7s300_ik",
    "irb120_ik": "abb.irb120_ik",
    "irb1600_ik": "abb.irb1600_ik",
    "irb6700_ik": "abb.irb6700_ik",
    "kr6_r900_ik": "kuka.kr6_r900_ik",
    "kr210_r2700_ik": "kuka.kr210_r2700_ik",
    "gp8_ik": "yaskawa.gp8_ik",
    "rs007n_ik": "kawasaki.rs007n_ik",
    "lrmate200id_ik": "fanuc.lrmate200id_ik",
    "r2000ic210l_ik": "fanuc.r2000ic210l_ik",
    "rx160_ik": "staubli.rx160_ik",
    "rm75_ik": "realman.rm75_ik",
    "gen72_ik": "realman.gen72_ik",
    "cr5_ik": "dobot.cr5_ik",
    "nova5_ik": "dobot.nova5_ik",
    "rv4fr_ik": "mitsubishi.rv4fr_ik",
    "hh020_ik": "hyundai.hh020_ik",
    "vs060_ik": "denso.vs060_ik",
    "m1013_ik": "doosan.m1013_ik",
    "m0609_ik": "doosan.m0609_ik",
    "hc10_ik": "yaskawa.hc10_ik",
    "xmatepro7_ik": "rokae.xmatepro7_ik",
    "xmatecr7_ik": "rokae.xmatecr7_ik",
    "xmatesr3_ik": "rokae.xmatesr3_ik",
}

_PKG = __name__  # "ssik.prebuilt"


class _LegacyAliasFinder(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    """Resolve ``ssik.prebuilt.<legacy_flat_name>`` to its vendor module,
    lazily -- so every pre-#421 import form keeps working after artifacts
    moved into vendor subpackages. Fires only for the exact legacy names.
    """

    def find_spec(
        self, fullname: str, path: object = None, target: object = None
    ) -> importlib.machinery.ModuleSpec | None:
        prefix = _PKG + "."
        if not fullname.startswith(prefix):
            return None
        leaf = fullname[len(prefix) :]
        if "." in leaf or leaf not in _LEGACY_ALIASES:
            return None
        return importlib.machinery.ModuleSpec(fullname, self)

    def create_module(self, spec: importlib.machinery.ModuleSpec) -> object:
        leaf = spec.name[len(_PKG) + 1 :]
        real = importlib.import_module(_PKG + "." + _LEGACY_ALIASES[leaf])
        sys.modules[spec.name] = real
        return real

    def exec_module(self, module: object) -> None:  # already the real module
        pass


sys.meta_path.append(_LegacyAliasFinder())


class PrebuiltArm(NamedTuple):
    """One row of the prebuilt catalog (see :func:`list_arms`)."""

    name: str  # legacy flat module, e.g. "fanuc_crx10ia_ik"
    vendor: str  # subpackage, e.g. "fanuc"
    import_path: str  # e.g. "ssik.prebuilt.fanuc.crx10ia_ik"
    display_name: str
    dof: int
    kinematic_class: str


def list_arms(vendor: str | None = None) -> list[PrebuiltArm]:
    """Return the catalog of prebuilt arms, read from the manifest.

    Imports **no** arm artifact -- pure metadata, safe to call after a bare
    ``import ssik``. Pass ``vendor=`` to filter (e.g. ``"universal_robots"``).
    """
    from ssik.prebuilt._manifest import load_manifest

    out = [
        PrebuiltArm(a.name, a.vendor, a.hier_module, a.display_name, a.dof, a.short_class)
        for a in load_manifest().values()
        if vendor is None or a.vendor == vendor
    ]
    return sorted(out, key=lambda a: (a.vendor, a.name))


def vendors() -> list[str]:
    """Sorted list of vendor subpackages that ship prebuilt arms."""
    return sorted({a.vendor for a in list_arms()})


def __getattr__(name: str) -> ModuleType:  # PEP 562: ``from ssik.prebuilt import ur5_ik``
    # Return type is ``ModuleType`` (not ``object``) so mypy keeps resolving the
    # legacy flat form ``from ssik.prebuilt import ur5_ik`` to a module -- its
    # attributes type as ``Any`` rather than erroring. The preferred hierarchical
    # import ``from ssik.prebuilt.universal_robots import ur5_ik`` resolves to the
    # real submodule file and keeps precise types.
    if name in _LEGACY_ALIASES:
        return importlib.import_module(_PKG + "." + _LEGACY_ALIASES[name])
    raise AttributeError(f"module {_PKG!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    static = ["list_arms", "vendors", "PrebuiltArm"]
    return sorted(
        set(_LEGACY_ALIASES) | {v.split(".")[0] for v in _LEGACY_ALIASES.values()} | set(static)
    )
