#!/usr/bin/env python
"""Emit a native C++ artifact header + FK parity fixture for one arm (#488).

Phase-0a scope: Band-A constant rendering (the KinBody -> a ``JointConsts``
struct) plus a Python-computed FK parity fixture so the C++ side can be checked
against the reference at machine precision. This is the CppRenderer precursor
for #482; it will fold into ssik.core.codegen behind ``--target cpp`` once the
solver bands land.

Usage: ``python scripts/cpp_emit.py <arm> [--out-dir cpp/gen]``  (e.g. ur5_ik)
"""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path

import numpy as np

from ssik.kinematics.poe_fk import poe_forward_kinematics

_REPO = Path(__file__).resolve().parent.parent


def _f(x: float) -> str:
    """Full-precision C++ double literal (round-trips exactly)."""
    return repr(float(x))


def _mat4(m: np.ndarray) -> str:
    m = np.asarray(m, dtype=np.float64).reshape(4, 4)
    rows = ",\n       ".join(", ".join(_f(v) for v in row) for row in m)
    return f"(Eigen::Matrix4d() <<\n       {rows}).finished()"


def _vec3(v: np.ndarray) -> str:
    v = np.asarray(v, dtype=np.float64).reshape(3)
    return f"Eigen::Vector3d({_f(v[0])}, {_f(v[1])}, {_f(v[2])})"


def emit(arm: str, out_dir: Path, n_parity: int = 200, seed: int = 0) -> None:
    mod = importlib.import_module(f"ssik.prebuilt.{arm}")
    kb = mod._KB
    joints = kb.joints
    dof = len(joints)
    ns = arm  # e.g. ur5_ik

    # --- Band A: the JointConsts struct -------------------------------------
    lines: list[str] = [
        "// AUTO-GENERATED by scripts/cpp_emit.py -- do not edit.",
        f"// Native kinematic constants for {arm} ({dof}-DOF), rendered from the KinBody.",
        "#pragma once",
        "",
        '#include "ssik_cpp/fk.hpp"',
        "",
        f"namespace ssik::{ns} {{",
        "",
        f"constexpr int DOF = {dof};",
        "",
        "inline JointConsts<DOF> consts() {",
        "  JointConsts<DOF> c;",
    ]
    for i, j in enumerate(joints):
        jt = "Revolute" if j.joint_type == "revolute" else "Prismatic"
        lines.append(f"  c.axis[{i}] = {_vec3(np.asarray(j.axis))};")
        lines.append(f"  c.t_left[{i}] = {_mat4(np.asarray(j.T_left))};")
        lines.append(f"  c.t_right[{i}] = {_mat4(np.asarray(j.T_right))};")
        lines.append(f"  c.type[{i}] = JointType::{jt};")
    lines += ["  return c;", "}", "", f"}}  // namespace ssik::{ns}", ""]
    art = out_dir / f"{arm}.hpp"
    art.write_text("\n".join(lines))

    # --- FK parity fixture (Python reference) -------------------------------
    ranges = [
        (float(j.limits[0]), float(j.limits[1])) if j.limits else (-np.pi, np.pi) for j in joints
    ]
    rng = np.random.default_rng(seed)
    fx: list[str] = [
        "// AUTO-GENERATED by scripts/cpp_emit.py -- do not edit.",
        f"// {n_parity} (q, fk(q)) cases for {arm}, computed by the Python reference.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <vector>",
        "",
        f'#include "{arm}.hpp"',
        "",
        f"namespace ssik::{ns} {{",
        "",
        "struct FkParityCase {",
        "  std::array<double, DOF> q;",
        "  std::array<double, 16> fk;  // row-major 4x4",
        "};",
        "",
        "inline const std::vector<FkParityCase>& fk_parity_cases() {",
        "  static const std::vector<FkParityCase> cases = {",
    ]
    for _ in range(n_parity):
        q = np.array([rng.uniform(lo, hi) for lo, hi in ranges])
        t = poe_forward_kinematics(kb, q)
        qstr = ", ".join(_f(v) for v in q)
        tstr = ", ".join(_f(v) for v in np.asarray(t).reshape(16))
        fx.append(f"    {{{{{qstr}}}, {{{tstr}}}}},")
    fx += ["  };", "  return cases;", "}", "", f"}}  // namespace ssik::{ns}", ""]
    (out_dir / f"{arm}_fk_parity.hpp").write_text("\n".join(fx))

    print(f"[cpp_emit] {arm}: DOF={dof} -> {art.relative_to(_REPO)} + {n_parity} FK parity cases")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("arm", help="prebuilt arm name, e.g. ur5_ik")
    ap.add_argument("--out-dir", type=Path, default=_REPO / "cpp" / "gen")
    args = ap.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    emit(args.arm, args.out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
